module.exports = {
  CNPM_REGISTRY: 'http://r.cnpmjs.org',
  NPM_REGISTRY: 'http://registry.npmjs.org',
  TAOBAO_REGISTRY: 'https://registry.npm.taobao.org',
  TEAMBITION_REGISTRY: 'http://npm.dev22',
  GITLAB_REPO: 'git@code.teambition.com:tbfe',
  GITHUB_HOST: 'https://github.com',
  OPTIONAL_VERSION_LIB_LIST: [
    '@teambition/clarity-design',
    'react',
    'react-dom',
    'react-router',
    'react-router-dom',
    'redux',
    'react-redux',
    'react-router-redux',
    'mobx',
    'mobx-react',
    'typescript',
    'tslint',
  ],
  TYPES_LIB_LIST: [
    '@types/node',
    '@types/react',
    '@types/react-dom',
    '@types/react-router',
    '@types/react-router-dom',
    '@types/react-redux',
    '@types/react-router-redux',
    '@types/mobx',
    '@types/mobx-react',
  ],
  OPTIONAL_MAIN_VERSION_LIB_LIST: [
    'webpack',
    'webpack-dev-server',
  ],
  LATEST_VERSION_LIB_LIST: [
    'tb-icons',
    'tslint-eslint-rules',
    'tslint-react',
    'stylus',
    'style-loader',
    'css-loader',
    'stylus-loader',
    'postcss-loader',
    'ts-loader',
    'file-loader',
    'url-loader',
  ],
  OPTIONAL_LIB_LIST: [
    '@teambition/rrule',
    '@types/rrule',
    'teambition-sdk',
    'reactivedb',
    'mocha',
    'karma',
    'chai',
    'jest',
    '@types/jest',
    'enzyme',
    '@types/enzyme',
  ],
}
